### ISSUE TITLE
Some feature discussion/requests

### ISSUE THREAD

**Issue by alexjbest** [asmjit/asmjit#124]
Hi Petr (and others),

Firstly thank you work writing asmjit, it really useful for a project I am working on and I'm enjoying using it.

There some extra features it would be good for me if asmjit (specifically Assembler) supported.
I am very happy to work on all of these myself, but I want to get some an idea of how these features fit in to your idea of how asmjit should work. This way hopefully some of these could be incorporated into the main asmjit rather than just bitrotting in my personal version. So if you have thoughts on what the _right_ way any of the following should be done (rather than me just hacking things together) I would love to hear them. I am not a C++ expert (in fact this is the first time I've properly used the language) so there are probably better ways of doing some of these things than what I have in mind.
Some of these might be possible already, and I've just missed how to do them, I'd love to hear about that too.
1. AT&T / GAS syntax for assembler logger output, for my purposes it is more convenient to use this syntax so it would be good if logger could do this. I have put together a basic version of this already but I don't know if you want this in asmjit, and if so where you think the option for this should go?
2. Support for shift instructions without argument e.g. `shr rax` is assembled as `shr rax,1`.
3. Support for the additional (illegal?) `rep` instruction `repz ret`, this is apparently better for the branch predictor than `ret` on some AMD processors (wtf...). I think this is possibly better dealt with in my code.
4. Instruction reordering on the assembler level. I would like to be able to reorganise instructions after they are emitted (maybe even after they are moved to executable memory). Currently to do something like this I reset my assembler instance and re-emit the instructions I have in a different order, this is a bit clunky. I saw some comments mentioning this being a planned feature but I am not sure what the plan is for this. Like I said above I'm happy to work on this if I know what approach you intend.
5. Related to number 4: make labels resettable, currently for me to reorder instructions I have to make new label objects every time I re-emit the code, it would be nice if there was some way of completely resetting labels so that they may be reused, but I can't find one currently.
6. A way within asmjit of telling generally which operands instructions read from and write to. Maybe some sort of getOFlagsIn/Out?
7. A getRegByName function similar to getInstIdByName. This I do currently with several lines of macros, if there was a more programmatic (and extendible) way to achieve this that would be nice.

In case you are interested in what I want all these for: I am working on an optimiser for assembly code that takes existing assembly and reorders the instructions to find which ordering executes in the least time. Doing this all in memory is probably preferable to writing to files (though to be honest I never actually tried this) so I am using asmjit for this purpose.

If you happen to have any other thoughts on aspects of asmjit that I might be able to make use of, or any feature ideas that you want implemented that you think would be useful for me I'd be interested to hear about those too.

Thanks again,
Alex

**Comment by kobalicek** [comment]
Hi Alex, thanks a lot for your suggestions!

1. This was never planned by me as I tried to keep asmjit lean and mean, however, this can be implemented as a part of a disasm interface I was thinking about in the past. The idea was to be able to attach a disasm to assembler so the shown assembly is not generated by asmjit, but by a third party library. This can help to reveal bugs as well. I'm not completely against having also AT&T logging built-in, but I found the syntax to be weird personally :)

2. This is possible, never thought about it as I tried to make Assembler and Compiler as close as possible. I don't mind to write the implicit `1`, but it's possible, a little work on `X86Assembler` actually.

3. I had to google this. I have never heard of this before, but I'm fine with having this one.

4. 5. I wanted these, but not part of an `Assembler`, but `Stream`. I have already started the work, but never finished it. The idea is to have something like Compiler, but without all the high-level concepts. I designed the `CodeGen` interface for that. We should definitely talk about this, I have a pretty good idea about how it should be implemented, and if you wanna start working on reordering I'm able to reschedule my internal plan to move this to be my top priority.

6. GetOFlags was intended to do this, however, the problem is that on x86 this is a bit difficult without having the full operand list of the instruction. I think that there should be a new API, something like `analyzeInstruction(code, options, operands[])` that will return everything it knows about it. The compiler already does this, but it's a bit hacky if you look at it (there are a lot of special cases on x86, ARM would be easier).

7. That's possible, but to create a full asm from string you would need to support memory operands, etc. Hard to say if this should be part of asmjit or not. I initially planned a thirt party lib that will be able to parse a string and serialize to X86Assembler. I included instruction names lookup because asmjit already knows the list and uses it when you turn on logging.

Yeah, your goals are interesting also for me, I want instruction reordering to be part of asmjit, because in my other project (blend2d.com) I generaly pipelines that can execute faster if reordered properly.

We should definitely discuss all the ideas here or on some chat. Maybe I should setup gitter for asmjit as well?

**Comment by diakopter** [comment]
@alexjbest could you post the macros you use for #7 ?

**Comment by kobalicek** [comment]
For 7 you would need to return a generic register, like `Reg`, there is already an implementation that is part of asmtk, here:

  https://github.com/asmjit/asmtk/blob/master/src/asmtk/asmparser.cpp#L113

**Comment by alexjbest** [comment]
@diakopter The asmtk method is probably the best option now that it exists (nice job btw @kobalicek !). But for the sake of completeness the current version of the macros I was using (which were recently improved by @akruppa)  are in https://github.com/akruppa/ajs/blob/master/ajs_parsing.h .

**Comment by kobalicek** [comment]
Is anything here still relevant, my opinions are as follows:

  1. GAS Syntax - not planned, I think the current Intel/nasm/yasm syntax is pretty good, at&t would mean adding even more strings to asmjit and more logic to handle all the differences.
  2. Implicit shifts - I decided not to go with this, less ambiguity is always better.
  3. `rep ret` - I'm in favor of this one, still need it?
  4. Reordering - It will not be part of `Assembler`, but custom passes that can reorder instructions are planned, I even started https://github/asmjit/cult project to get some data.
  5. Rebinding labels - Use `CodeBuilder` for this - `Assembler` will never reset labels as when `bind` is called all existing relative offsets to that label are patched, relocations remain.
  6. Input/Output - Yes, asmjit has all the data now, including flags and special regs, only a function that returns it in some form is needed, I can work on this.
  7. Parsing - Already answered, `asmtk`, however, if justified, the register parser could be moved to asmjit, but it would have to be strong arguments to do so.

Let me know if you need `3` and `6`, these are possible to do meanwhile I work on other features.

**Comment by kobalicek** [comment]
The `rep ret` feature is already implemented in `next-wip` and there is also an initial work to provide read/write information, which will be improved. I'm closing this one as there was inactivity. Please reopen if I missed anything else.

**Comment by alexjbest** [comment]
Thanks Petr @kobalicek as you noticed, I am not working on this project currently. But at the time I really appreciated all detailed responses and help! If I come back to this I'm sure rewriting it with your new features should be a lot nicer.
