### ISSUE TITLE
Errors copying virtual args

### ISSUE THREAD

**Issue by MichaelRFairhurst** [asmjit/asmjit#152]
I changed an interpreter I had which stored results in a std::stack to storing registers. Therefore, all VarExpressions created a virtual register, set its arg index, put it on the stack, and returned.

```
X86Gp arg = cc.newInt64();
cc.setArg(..., arg);
stack.push(arg);
```

This seemed to behave strangely, so I figured the issues were from creating new virtual registers to represent the same arg multiple times. In `x + x`, the above code snippet will run twice and create two virtual registers representing arg 0. I'm assuming this isn't supposed to be allowed.

So I tried creating the arg vregs up front and storing them in a vector

```
for(int i = 0; i < argCount; ++i) {
  X86Gp arg = cc.newInt64()
  cc.setArg(i, arg);
  vector.push_back(arg);
}
```

But here I get a segfault (valgrind blames operand.h:203) when I add it to the vector.

Registers are supposed to be safe to copy and move, right? Is it safe to copy virtual registers? Argument registers?

I'm weirded out by having been able put it in a std::stack but I'm chalking that up to undefined behavior.

If its not safe to copy them after calling setArg, that is clunky to put in unique_ptr given the api is all value based.

**Comment by kobalicek** [comment]
Do you have some simple code that demonstrates the issue? `Operand` and all others like `Mem`, `Reg`, etc are safe to copy by value as they are not pointers, they only store IDs. Copying a virtual register doesn't create a new register - it's still the same.

So basically the code such as:

```c++
std::vector<X86Gp> regs;
regs.push_back(asmjit::x86::eax);
```

should work, I haven't tried, but it should work out of box.

So based on what I see I would first check if you are on 64-bit arch, as creating int64 when targeting 32-bit arch is not allowed as that arch doesn't have such register type (and if you need 64-bit in you have to use 2 regs by yourself basically, asmjit doesn't abstract this kind of stuff).

Then, I would enable debug builds, as they may help a lot when it comes to these kinds of problems and turn on logging and error handling (plug your error handler that prints the error at least, if you did anything wrong it will show up, because maybe the segfault is a consequence of something else).

**Comment by MichaelRFairhurst** [comment]
What seemed straightforward before seems to not be straightforward after
all. Imagine that, in c++.

Here's my theory: I'm using a hacky makefile right now. After adding the
vector member to my class, I didn't recompile my main() method because my
makefile is too simple. Garbage (but not of the type valgrind can detect)
was being interpreted as a vector, causing the clone operation to copy
memory from a bad segment.

Thanks for responding so quick!

**Comment by kobalicek** [comment]
Glad it works, enjoy using asmjit :+1:
