### ISSUE TITLE
Asmjit api and memory management

### ISSUE THREAD

**Issue by dibyendumajumdar** [asmjit/asmjit#166]
Hi,

I notice that the Asmjit api calls return objects rather than pointers to objects. This is problematic as it a) poses the question of memory management. What should be scope of the object? And b) in code generation scenarios we often need to store objects for later use. How can we do that?

I am thinking of example such as:

```
  Label L_Loop = cc.newLabel();           // Start of the loop.
  Label L_Exit = cc.newLabel();           // Used to exit early.

  X86Gp dst = cc.newIntPtr("dst");        // Create `dst` register (destination pointer).
  X86Gp src = cc.newIntPtr("src");        // Create `src` register (source pointer).
  X86Gp cnt = cc.newUIntPtr("cnt");       // Create `cnt` register (loop counter).
```

We typically want to store the label instruction somewhere and later refer to it. How can we do that in the example above?

I think the api should be like that of LLVM or Nanojit - return pointers to objects that are managed by the JIT. And it should be made explicit what the lifetime are for such objects - e.g. in LLVM all allocated objects are destroyed when the context is deleted.

It may be that the use case I have described above is already covered but this is not clear from the docs I have read so far.

Thanks and Regards
Dibyendu

**Comment by kobalicek** [comment]
I'm not sure if the documentation is not clear in this regard, but all `Operand`s in asmjit are passed by value. You can copy them, move them, store them, they will still refer to the same internal data asmjit maintains, if any.

If you know a bit internals you can also extract information from `Operand`s and store it completely separately, and then reconstruct these operands. The reason asmjit doesn't return pointers in this case is that:

  1. It's not necessary - operand has 16 bytes and asmjit can fit everything into this structure - including physical registers, virtual regiters, memory operands, immediates, and labels.
  2. Since asmjit manages its memory and uses zones, it would be extremely dangerous to invalidate these pointers when you destroy `CodeHolder` - everything returned would be dangling pointers in that case.

Maybe specifying more the problems you are dealing with would help me to understand the root of the issue you have.

**Comment by dibyendumajumdar** [comment]
Hi - okay thanks for explaining! Now that you have clarified I also see this in the document. 

I am curious about the relatonship between an operand and the CodeHolder. If the CodeHolder is destroyed and I still have an operand created from it then what is the status of this operand?

Thanks and Regards

**Comment by kobalicek** [comment]
It depends on the type of the operand. If the operand is a physical register nothing really happens. If the operand is some Label that doesn't really exist anymore, then the Label id would be wrong, but the operand doesn't have any pointer to a dangling data, just the id would be invalid. asmjit always checks IDs before it uses them to dereference internal data, so in the worst case asmjit will just return an error, for example `kErrorInvalidLabel`, `kErrorInvalidVirtId`, `kErrorInvalidPhysId`, etc.

**Comment by dibyendumajumdar** [comment]
That means though that it is no different if the operands were returned as pointers, right? 

Anyway I now understand that I can store an operand for later use. But a 16-byte value is still inconvenient, compared to a pointer. I am planning to use asmjit as the backend in a C compiler - currently the frontend provides a void* to the backend to hold references it wants to. Using a 16 byte value therefore is not possible. I can amend the frontend to hold values but then the code becomes tied to asmjit. Whereas really the backend is currently independent of the frontend.

Regards
Dibyendu

**Comment by kobalicek** [comment]
It depends on how long you are planning to store these values. Typically operands in asmjit does't have a long life-time, you create them, possibly store them, use them, they die. I mean you can keep them, you can extract data and reconstruct it when possible, you can create pointers to operands on your own, there is no limitation basically.

For example suppose you have a label, but 16 bytes are so much?

```c++
asmjit::Label label = ...;

uint32_t labelId = label.getId();
// Forget about label...

// Recreate the label
asmjit::Label anotherLabel(labelId);
// You have it back
```

Similar stuff can be done with physical registers, virtual registers, etc, but I would recommend to simply not do that, and especially not at the beginning of a project. Since Operands are not pointers there is no overhead in creating them, and you can modify them on-the-fly. Suppose this construct:

```c++
X86Gp someReg = ...;
a.movzx(someReg.r32(), someReg.r8());
```

You create these operands on-the-fly, they are zero cost, no allocations needed, etc. With pointers you would have to create these objects first, then keep them to make sure they stay valid until the end of the lifetime of `CodeHolder` or `CodeEmitter`.

I think once you fully understand the design and its potential you would be happy it was designed this way - no pointers, no management, everything up to you.

**Comment by dibyendumajumdar** [comment]
I only need to store stuff while generating code. The code is generation off the IR generated by the frontend, each IR instruction is processed sequentially. So stuff needs to be stored so that later instructions can access previously created operands, labels, registers, stack locations, etc. 

I assume that the when operands are passed to instructions they are passed as base type? Or is it necessary to cast each operand to expected type? 

With regards to the design I understand the rationale, but the important thing is that all memory is managed by the JIT engine, so that it doesn't matter whether one is dealing with pointers or values. I don't think there is any advantage to using values as opposed to pointers as used by LLVM, for example.

Thanks and Regards
Dibyendu

**Comment by kobalicek** [comment]
Maybe sharing the code you work on would be much better than discussing it in theory. Or maybe at least some snippets. If you generate code based on existing IR you may already have registers allocated, so you don't need to store any asmjit operands and you can just generate them on the fly if your code is done.

When it comes to labels you can use asmjit to just give you Label ID and generate Label operands on-the-fly as well. Storing label ID requires less storage than storing a pointer, in 64-bit mode, so it should be even better storage-wise.

AsmJit is highly dynamic, you don't need to cast anything if you use the untyped API, for example:

```c++
using namespace asmjit;
X86Assembler a = ...;

uint32_t aPhysId = 0;
uint32_t bPhysId = 0;

Operand x = x86::gpd(aPhysId);
Operand y = x86::gpd(bPhysId);

a.emit(X86Inst::kIdMov, x, y);
```

Typed API is just a sugar on top of the untyped API. People that want their instructions checked by C++ compiler use typed API. Untyped API is perfect if you need higher flexibility and constructing operands and instructions dynamically.

I'm wondering why not to just use LLVM if the design fits your use-case better. AsmJit and LLVM are completely different tools suitable for different tasks - if LLVM works for you then I would recommend to just use it.

Maybe sharing your code and explaining what you want to do would help me to understand where you see the issue and I may be to help. Maybe joining gitter and talking with people that already used asmjit for similar things would work too.

**Comment by dibyendumajumdar** [comment]
> Maybe sharing the code you work on would be much better than discussing it in theory. Or maybe at least some snippets. If you generate code based on existing IR you may already have registers allocated, so you don't need to store any asmjit operands and you can just generate them on the fly if your code is done.

I don't have an asmjit implementation yet. The LLVM implementation is here: https://github.com/dibyendumajumdar/dmr_c/blob/master/llvm-backend/sparse-llvm.c

> AsmJit is highly dynamic, you don't need to cast anything if you use the untyped API, for example:

> Typed API is just a sugar on top of the untyped API. People that want their instructions checked by C++ compiler use typed API. Untyped API is perfect if you need higher flexibility and constructing operands and instructions dynamically.

That is probably the approach I will need to take.

> I'm wondering why not to just use LLVM if the design fits your use-case better. AsmJit and LLVM are completely different tools suitable for different tasks - if LLVM works for you then I would recommend to just use it.

LLVM backend is there - I have been fixing bugs. My plan is to keep it as an alternative, however, LLVM is a huge thing and I need a lightweight alternative which may not generate as optimum code but is very small and fast. I want to use asmjit for this. 

Thank you for answering the questions. I was stuck initially with the question of how to store the operands, but this is now resolved. I will need to change the way the backend stores this currently.

I think this issue can be marked as resolved.

Many thanks
Regards
Dibyendu

**Comment by kobalicek** [comment]
Thanks for the link, it's a very interesting project indeed.

Keep in mind that asmjit is not an IR, so all the things it provides basically map at some level to asm instructions. CodeBuilder and Function helpers are the only two high-level concepts asmjit provides to make the code generation easier.
