### ISSUE TITLE
about operand struct

### ISSUE THREAD

**Issue by lyrachord** [asmjit/asmjit#186]
Hi kobalicek,
Current internal operand use 2 8-byte items. 
The main cause is the move offset/imm64 instructions?
If so, I tried a way to avoid the 8-byte overhead:
split offset/imm64 into 2 offset/imm32. 

Without the 8-byte, all other structs should be smaller.

cheers

**Comment by kobalicek** [comment]
Well, operands generally require the following:

  * Register Operand (requires 64 bits):
    * Signature (32-bit)
    * RegId (32-bit)
  * Memory Operand (requires 128 bits):
    * Signature (32-bit, BaseType (5 bits), IndexType (5 bits), scale (2 bits), segment override (3 bits), broadcast (5 bits), and other flags)
    * BaseId (32-bit RegId or LabelId, possibly combined with a HiOffset for absolute 64-bit addresses)
    * IndexId (32-bit)
    * LoOffset (32-bit, always provided).
  * Label (requires 64 bits):
    * Signature (32-bit, not fully used)
    * LabelId (32-bit)
  * Immediate Value (requires 96 bits)
    * Signature (32-bit, not fully used) 
    * ImmValue (64-bit) - it must be 64-bit as mov allows 64-bit immediate and ARM allows various combinations to form 64-bit masks and floats

These make it impossible to shrink the type to store RegId and LabelId:
  * RegId is 32-bit, where values less than 255 (0xFF) are PhysRegs, and values greater than 255 are VirtRegs
  * LabelId is 32-bit

I think it's impossible to decrease the size of the struct. And since Operand is designed to hold any operand (so you can store anything in just `Operand`) it's impossible to make it smaller. Also, even if you think about making RegId 8-bits and not using it to represent virtual registers the maximum bits it can possibly save is 24 (Memory operand, BaseId/LabelId is stored together, so you can only shrink IndexId), which will not even save 4 bytes to make the struct 12 bytes.

I think personally it's quite an achievement to have the Operand only 16 bytes long, I refactored it many times to reach the current structure and personally I would not want to have it greater than 16 as that would be unnecessary overhead. 64-bit immediates and addressing makes it impossible to have it less than 12 bytes in any case, so I think it's pretty good deal.

**Comment by lyrachord** [comment]
Great!
I did not yet dig into how operands to pass to processing in asmjit.

My idea is 
1,  For a byte8 offset and imm operand, split it to 2 operands, called high and low part. Instruction description changed as  well, of cause, internally. The sort of instructions only mov. It seems it's not a problem in x86. As to ARM64, I need to check it out again.

2, The biggest problem is the pointer. Because complicated cases not so frequent, based on this point, split a pointer to multiple parts, say, base, sib, disp. "base" is the main part, and the pipeline knows how many latter parts follow through the main "base". I guess, we can get a whole byte8 only operand struct.

3, Another point. patching. Not remember if there is a mem-to-mem transfer mode, so just in x86. There is only one memory pointer operand. Modelling the main part as operand, take other parts as instruction patching. So the internal instruction representation like this: opcode, operands(main), patching. If the patching can do no participating in the pipeline,  I guess, the main-pointer-operand can be smaller.

**Comment by kobalicek** [comment]
1) That would make the API a nightmare to use. Currently it's 1:1 mapping to ISA with few extensions mostly related to <implicit> operands. 64-bit immediate values are commonly used in mov instruction, so this use-case must be supported by default (without splitting the operand).

2) Memory operands where both base and index registers are used are frequent, and also base + offset. These need at least 64 bits just for IDs, so it's impossible to shrink the struct to less than 12 bytes in any case.

3) Currently patching is very easy as you can just modify operands. There is at least one case where instruction contains two memory operands which is explicit form of `movsb|movsw`.

I really think you should dig into it and see that even now the data in operand is really used to full extent and there is no waste. I would also like to prevent design flaws now that would make it impossible to port asmjit to more architectures. Currently I only plan ARM, but my long term plan is also MIPS and RISC-V.

BTW: If you think operand is too bit overhead you can always transform asmjit operand into your own representation. You can decompose / compose the struct easily. I would like to prevent anything that would make it hard to use and that would also slow-down instruction processing.

**Comment by lyrachord** [comment]
Before the session, I think, there are a key point to be clear to avoid missing in direction that it's just a discussion and not to try to change the design of asmjit

Thank you for your advice. I back from code.
Well, begin with a cliche: Each method has its use cases to apply which is assumed and created by one.
Since "use cases", there must be questions: how to use, why use, and so on.
The main scenario is x86 which I mentioned it before. Emphasizing it again, it means that my idea maybe has some limitations.  But x86 is CISC, since it's C, it implies RISC easier. BTW maybe AVR, JVMBytecode as well.

Forget size of operand. Let's check out code, which simplified by a simple syntax to emphasize the key points
```d
alias e = emitter

Gp dest = e.z(0)
Gp src_a = e.z(1)
Gp src_b = e.z(2)

Vec v0 = xmm0
Vec v1 = xmm1

//function header build ignored here

e.movdpu(v0, pointer(src_a))
e.movdpu(v1, pointer(src_b))
e.paddd(v0, v1)
e.movdqu(pointer(dest), v0)
```
the first:
```d
gp = e.z(n) 
```
there is a receiver e and 
z is context size senstive. 
so the creation of gp needs a context, 
one should be able to catch it if he is aware of operation mode of cpu

vec constant ignored here
now almost the last, check out this instruction
```d
e.movdpu(v0, pointer(src_a))
```
there are 2 points: nemonic and pointer
nemonic, it implies instruction, and it should be in a operation mode. fine.

now pointer
asmjit pointer uses a form without context: 
```d
alia pointer = x86::ptr(...)
```
becuase there is no context, so the result operand must be alone, which must contain all payloads.

In deed there already has a context, emitter, and z registers in front used it.
Now if let the context do creation of pointer, how to code?
```d
alias pointer = e.ptr(...)
e.movdpu(v0, pointer(src_a)) //or 
e.movdpu(v0, e.ptr(src_a))
```
But what happend underlying emitter?
```d
alias operand = pure struct //almost, z make it not pure.
now asmjit do: _emit(operand1, operand2, ....){
	//deconstruct operand struct
}
```
assembler with payload maybe like this:
```d
alias operand = pure struct //can be absolutely pure, it's just a header
_emit(operand1, operand2, ...operandN, payload){
	//no need to deconstruct
	//payload, it is 
}
```
for coding, maybe reverse parameters
```d
_emit(payload, operand....)
```

**Comment by kobalicek** [comment]
You only need the emitter to make cross-platform assembling easier, it's def not needed to construct and work with operands. In the case you mentioned `gpz` it's just a context to give the register correct signature, it's not an extra payload.

You can also construct arch-specific GP without the emitter, like this:

```c++
Gp makeArchReg(uint32_t targetArch, uint32_t rId) {
  return Gp(targetArch == Arch::kTypeX86 ? Gpd::kSignature : Gpq::kSignature, rId);
}
```

So the `emitter` in your example is just `targetArch` holder, it has no other payload when it comes to constructing operands. The reason why you can just use `x86::ptr()` to construct memory operand for XMM load is that the size of the operand is known at compilation time.

I'm not sure how to describe this better, in general asmjit doesn't require a context to construct operands, you can create instructions and operands independently and then for example just validate them, or analyze them, or do whatever else with the built-in database asmjit provides, the context is only required for assembling in general.

BTW there is also a gitter chat you can use to discuss ideas.

**Comment by lyrachord** [comment]
1, My gitter seems not to work fine.
2, At Gz point, it seems that I did not make it clear. IMO notations like Rv, Iz, should stand for my knowledge on this section.
3, The core point of code above is still to try to make operand struct smaller.
	I try to write coherently.

There core idea is:
If make operands to live in a context object, so the operand struct can be smaller.

back to above, there are an e.z(?) and an e.pointer
e.z(?) is not the point, and e.pointer(...) is the key.

now
An underlying context implementation maybe like this:
```d
Pointer context.pointer(Register index, base; int offset){
	auto m = createMemoryOperand(index, base, offset)
	internalStack.push(m.payload())
	return m.pointer()
}


context.emit(Opcode op, Operand o1, Operand o2...){
	//blabla
	...
	//encoding..
	if(o1 is Pointer) {
		auto payload = internalStack.pop()
		patching(instructionBuffer, o1, payload)
	}
}
```
context.pointer shows a memory operand is split to 2 components, 
the Pointer is just some kind of header value. 
now the Pointer component should be small.

But why do splitting?
Again, e.z(?) is not the point, it's an inducement occasion.
e.z(?) needs a context, and another operand type is Label, context sensitive.
Since there are some components which must require context, so take the context as a part of operand.
Since the context is considered, so the operand struct can be split.
Since the operand struct is split, so the operand struct can be smaller.

Please note there is a important thing that this c++ use case(here it's asmjit programming) has no GC. or we don't want to employ a GC. 
So we do manual work for payload management.
If writing in java or a GC-eanbled language, basically there is no need to make ourself to be entangled with Object management. Of cause, it does not matter here.

**Comment by kobalicek** [comment]
I still don't see how two operands are better than one 16-byte operand, and how data stored on context side is better than data stored within operand. From design perspective it looks like a nightmare. Operands are not independent of context, you only need context to make something context-aware like label (which is stored as id on operand side) and virtual register (which is again just id on operand side).

I designed operands in a way to NOT be pointers, to NOT require external memory management, because if they are pointer you would end up here:

  * Pointer requires 4 or 8 bytes, let's assume 8 bytes as majority of computing moves to 64-bit architectures.
  * If the operand is a pointer (8 bytes) and points to another 8 bytes you would need 16 bytes to store the data, and you would only use half of these 16 bytes as 8 bytes would be "pointer" to data.

What I mean is that I'm not really convinced this would be any better. Priority is to have nice API that one can work with, not to introduce unnecessary complexity.

**Comment by lyrachord** [comment]
There are 2 styles of api to build an instruction
1, function style
```d
	context.Nemonic(operand1, operand2,..)
```
most assemble languages use this style. Maybe internally we do:

```d
	form {
		nemonic=Nemonic;
		operands=[operand1, operand2, ..];
	}
```	
2, expression style, RPN 
```d
	context.op(operand1)
		   .op(operand2)...
		   .Nemonic()
	form {
		operands=[operand1, operand2, ..];
		nemonic=Nemonic;
	}
```

In other word, function style is stack as well
```d
	context.nemonic()
		   .op(operand1)
		   .op(operand2)...
		   .end()
```
But there must be a terminal, end() is.
Now we can say, both internal forms of 2 styles are same.

Back to function style, there is a problem, big operand! 
The representation of mem operand is the main reason. 
let's write an instruction using a mem operand with SIB form, (size ignored)
```d
context.mov(general, [g1<<1+g2+disp32])
```
here mem is [g1<<1+g2+disp32]
If api digned to use the whole operand, so this operand is big.
Furthmore, If in a higher builder layer, the mem may be bigger in company with other attributes, i.e.
```d
	bytes2 seg:[g1<<1+g2+disp32]
```	
Because it's big and cannot be got directly, so there must be a builder, say, Pointer:
```d
	context.move(general, Pointer.build(2, g1, g2, disp32))
```
here Pointer.build(2, g1, g2, disp32) return an operand, say, mem
as you see, it's 
```d
	context.move(general, mem)
```
Operand representation like this:
```d
	register{
		flags...
		kind, size, ordinal
	}
	memory{
		flags...
		category, size, payload bytes,
		scale, index, base, disp
	}
```	
Well, that's it.
Now let's focus on the instruction struct. Maybe...
An instruction representation looks like this:
```d
	instruction{
		nemonic,
		operand1,
		operand2,
		operand3,
	}
```
An operand can be register, number, memory.
Albeit there is only at most one memory operand, the memory operand makes all other operands bigger.
Consider to employ a payload way:
```d
	memory{header, payload}
```
there are ways to treat the payload, f.e.
```d
	payload{sib, displacement, immediate}
	payload{displacement, immediat}
```
	
Assumed the first one used, new memory operand looks like this	
```d
	memory{
		flags...
		category,
		size,
		number: payload bytes
	}
```	
And because operands always be in company with its own instruction, so move the payload to the instruction:
```d

	instruction old version{
		nemonic, 
		operand1, 
		operand2, 
		operand3, //memory{flags..,category, size, payload bytes, payload}
	}

	instruction{
		nemonic, 
		operand1, 
		operand2, 
		operand3, //memory{flags...,category,size, payload bytes}
		payload,
	}
```
now the Pointer builder mentioned before should be context sensitive.
Let the context do the build work
```d
	context.pointer(....)
	//context.move(general, Pointer.build(2, g1, g2, disp32))
	context.move(general, pointer(2, g1, g2, disp32))
```
How is the context.pointer(...) implemented?

```d
Context{
	Size: default operand, default address
	Size: operand, address
	other informations...
	
	Instruction currentInstruction;
	pointer(scale, index, base, disp32){
		//check size of index and base
		//check vsib...
		memory{
			if(index.size<default address) flags ~= address override
			if(disp32 is byte) flags ~= ByteDisp;
			category = sib;
			size=default,
		}
		currentInstrution.payload{
			scale, index, base, disp
		}
		memory.payload bytes = full
		
		return memory
	}
	Nemonic(o1,o2...){
		currentInstruction{
			operand1=o1
			operand2=o2
			nemonic = Nemonic
		}
		underlying.process(currentInstruction)
	}
}
```

Here, the pointer build a memory operand, and pass to instruct build method, it seems not so brilliant, so RPN form can be used:
```d
Context{
	Size: default operand, default address
	Size: operand, address
	other informations...
	
	int operandIndex;
	Instruction currentInstruction;
	
	//pointer operand build function family
	pointer(integer){...}
	pointer(register base) {...}
	....
	pointer(scale, index, base, disp32){
		//check size of index and base
		//check vsib...
		memory{
			if(index.size<default address) flags ~= address override
			if(disp32 is byte) flags ~= ByteDisp;
			category = sib;
			size=default,
		}
		currentInstrution.payload{
			scale, index, base, disp
		}
		memory.payload bytes = full
		currentInstruction[operandIndex]=memory
		operandIndex++		
	}
	
	//simple operand build function family
	op(register){
		...
		currentInstruction[operandIndex]=register
		operandIndex++
	}
	
	Nemonic(){
		underlying.process(currentInstruction)
		reset(operandIndex)
		clear(currentInstruction)
	}
}
```
Now the move instruction looks like this:
```d
	//context.move(general, Pointer.build(2, g1, g2, disp32))
	//context.move(general, pointer(2, g1, g2, disp32))
	context.op(general)
		   .pointer(2, g1, g2, disp32)
		   .move()
```
Indeed both call styles get same result. It's a question of taste.
And If there has template in a programming platform, memory can be still built by an outer builder and bigger than other kind of operands.
```d
op(memory) {
	currentInstruction[operandIndex]=memory.header
	current.payload = memory.payload
	operandIndex++
}
Nemonic<o2>(o1,o2...){
	currentInstruction{
		operand1=o1
		operand2=o2.header
		payload = o2.payload
		nemonic = Nemonic
	}
	underlying.process(currentInstruction)
}
```
I guess, we can get smaller version of operands by this way. 
Integers with 4 bytes should be enough.
What's more, because b4 is the default operand size in both b4 and b8 mode(many cases), so the program can get better performance.

Well, the next question: how to do underlying processing?
There may be 2 sorts of underlying: encoder and analyzer.
Both get an argument which is an Instruction struct which contains all operands information.
The instruction should be enough to optimize, or patch, such as relocating, resolving label..

**Comment by kobalicek** [comment]
I'm still not convinced. The proposed way is difficult from API perspective and I see no numbers that should support it. Without seeing an alternative implementation (which I will not write) and its metrics (performance, memory consumption, ease of use) I see no reason why this should change. It's stable and extensible right now, and I'm personally happy with the design (yeah I may change some bits here and there in the future, but I'm not planning to change the whole `Operand` and introduce another `Payload` structure to mess around with).

The thing is, the current API is very straightforward to use and operands are easy to build, inspect, and modify (AsmJit's compiler does that actually). Each AsmJit Operand represents a real instruction operand as described in architecture manuals. They are 16 bytes long and you can store any possible operand to a single `Operand` struct. I don't see a problem here considering this is part of AsmJit public API that you can use for many things - passing operands to assembler, builder, compiler, validator, logger, and inspector (some of them don't need emitter at all, so there is no context).

The problem with `Payload` is that you need to store it as well. I don't see any improvement in decreasing the size of A while introducing B which must be used with A.

Since operands can be composed and decomposed very easily I would suggest you to use your representation in your project and then just compose AsmJit operands from it before calling AsmJit API. That would solve your size constraints and would keep AsmJit design simple.

The size of the operand could only be a concern if you need to store like 1 billion operands, which would now take 16GB. In that case switching to some other representation internally would help more than changing the design of AsmJit.

**Comment by lyrachord** [comment]
The payload way is an essentially different design which make focus on the entirety of instruction instead of a combination of operands and opcodes. Let it go.

Back to asmjit, as to the reduction of operand size, re-abstracting the mem operand type maybe get a improvement.
There is a template
```d
//full size
enum Size : ubyte {
    b1, b2, b4, b8, 
    v1, v2, v4, bt,
}
//v means which starts from b8<<1
//bt means b10

//essential size
enum Bytes : ubyte {
    b1, b2, b4, b8, 
}
//bitfields it
///cases missed unit use bits
struct DirectAddress {
    long offset; //8bytes

    ubyte segment; //3
    ubyte category; //5
}

struct FarPointer {
    int offset; //4bytes
    short segment; //2bytes

    ubyte category; //5
}

struct EffectiveAddress {
    int offset; //4bytes

    ubyte cateogry; //5
    ubyte segment; //3

    Size valueSize; //3
    Bytes offsetSize; //2
    bool vector; //1
    ubyte indexBits; //2 only for VSIB

    bool relative; //1
    ubyte scale; //2
    ubyte index; //5

    ubyte base; //4
    ubyte indexSize; //2
    ubyte baseSize; //2

    bool mib; //1

    ubyte broadcast; //2 only 3 values, the last one as mask flag
    union {
        ubyte rounding; //2    
        ubyte mask; //2 contains zeroing
    }
}
```
I guess, 10bytes should be all right.
Even there may be a requirement for more register ids, the space is enough.

**Comment by kobalicek** [comment]
That would not work with virtual registers which require `uint32_t` as ID, so I don't see this going anywhere. Also, you forgot BASE as a label, which is still possible to use [label + index * scale + offset32], where label `uint32_t`, offset is `uint32_t`, which is 8 bytes already.

The problems with such proposals is that it makes it hard to work with it. Currently checking for baseReg, indexReg, etc is very simple, validation is simple, and rewriting operands is simple too, because the structure of Operand is simple.

I seriously think that you simply cannot shrink it to less than 16 bytes without sacrificing the design of asmjit. I will not agree with Payload as it complicates things, and I will not agree with shrinking operand to 15 bytes or 14 bytes for example, which doesn't make sense (alignment is 4, would be 16 anyway).

There are only few bits left in `Mem` unused and reserved for future use.

**Comment by kobalicek** [comment]
Closing as wont-fix. It would be really hard to decrease the operand size to anything else and it would mean a code change. The beauty of the current design is that operands are not dynamically allocated and I would like to keep it that way.
