### ISSUE TITLE
Relocate code that was not assembled by asmjit

### ISSUE THREAD

**Issue by MarkHC** [asmjit/asmjit#201]
Hello

I've looked through asmjit documentation and examples but I could not find anything that seems to accomplish what I need.

I am working on a code detouring library and I want to be able to relocate code that my detour will overwrite to another memory location (the trampoline).

I was thinking of adding the bytes that will be overwritten to a CodeHolder and then calling `relocate`  with the new address for the instructions, something like this:

```cpp
CodeHolder   code;

// Set the base address (codeBase)
code.init({ ArchInfo::kTypeX86, 0, (uint64_t)codeBase });

// This would add codeLength bytes, strating at codeBase address, to 
// this CodeHolder instance. Unfortunately such a function does not exist.
code.setCode(codeBase, codeLength);

// And then relocate the code to the new location
code.relocate(trampolineLocation);
```

Is there a simple way of doing this? I could iterate each instruction (with a library such as capstone) and then add them one by one to a X86Assembler but i'd rather avoid that if I could...

Thanks.

**Comment by kobalicek** [comment]
Hi Mark,

I'm afraid that relocate won't help you with your problem. Relocate function iterates over all RelocInfo entries stored in `CodeHolder::_relocations` and patches the code that RelocInfo refers to by possibly emitting a trampoline at the end of the code. The trampoline doesn't necessarily reflect how other relocators do it (it's not exactly GOT). In other words, it doesn't inspect the assembly in the buffer as it's only interested in RelocInfo entries.

RelocInfo entries are added to CodeHolder by X86Assembler in cases it cannot assemble a particular instruction because the base address is not known. This is the default behavior when emitting JIT code.

Maybe if you better explain what you are trying to accomplish I would be able to help you with asmjit use. There is also an active gitter channel that you can use if you want to chat about it.

**Comment by kobalicek** [comment]
BTW: To give you at least one hint. To embed some code into a CodeHolder you just need to create some emitter (like Assembler) and call `embed(data, size)` - but that's very similar to data embedding, it would embed the region you tell it without any knowledge about the data.

**Comment by MarkHC** [comment]
I see. I thought the behavior of `relocate` was different.

The problem I have is that, say I have the following instruction:

```asm
0x12345678: CALL SomeFunction
0x1234567E: <other instructions>
```

With 0x12345678 being the address of the instruction. If I were to place a detour on this location the `CALL` instruction that would be overwritten by my detour would be moved to another location (to be used as a trampoline for the old code). It would result in something like this:

```asm
0x12345678: JMP 0xAABBCCDD
0x1234567E: <other instructions>
....

0xAABBCCDD: CALL <???> ; Because CALL uses relative addresses as operand (IP based)
                       ; it is now broken. 

0xAABBCCE3: JMP 0x1234567E ; JMP back to the old control flow
```

The solution here is simple, you have to patch the CALL instruction to make it call the right place after being moved to this new memory location. The same thing is true for many other instructions so I thought AsmJit could help me with that :)

**Comment by MarkHC** [comment]
Anyways, got it to work for the most common cases (calls, conditional jumps, etc) using the Capstone engine to disassemble the code and patch any instructions that uses relative addressing

Might as well close this now as it's not related to asmjit in any way.

Thanks again!

**Comment by kobalicek** [comment]
I'm glad you made it working.

Just to note one thing - asmjit does essentially the same as you described, but you would have to use its X86Assembler `call` or `jmp` instructions or create RelocInfo yourself. If your solutions works for you then there is no need to do it as I don't know anyone who would add custom relocation information to asmjit.
