### ISSUE TITLE
Two operand NOP

### ISSUE THREAD

**Issue by DiskGetor** [asmjit/asmjit#217]
![image](https://user-images.githubusercontent.com/19886504/48675925-90b3e600-eb9a-11e8-8105-9195939c3e32.png)
![image](https://user-images.githubusercontent.com/19886504/48675932-98738a80-eb9a-11e8-8df3-4d2e373907e3.png)

**Comment by kobalicek** [comment]
I haven't found any documentation regarding two operand NOP instruction when I was adding single operand NOP. Providing a link to a documentation would be appreciated.

AsmJit can successfully encode a single operand `nop word [rax+rax * 1]` to `660F1F0400`, which sounds compatible, but I have no idea where this two operand nop comes from

**Comment by athre0z** [comment]
Since x64dbg uses Zydis, I might be able to shine some light on this. We disassemble it with two operands because that's what XED does, and generally XED tends to be right.

The according instruction definition in XED can be found here:
https://github.com/intelxed/xed/blob/master/datafiles/xed-isa.txt#L4622

**Comment by athre0z** [comment]
Well, I guess operands of nop instructions are among the least important things on earth. :D It pretty much only ever matters in the case of re-encoding.

The XED data tables contain quite a good amount of instructions that are otherwise undocumented in the SDM. If you ever feel like doing a full sweep through the XED tables and don't feel like parsing them yourself, be invited to check out or DB in JSON format:

https://github.com/zyantific/zydis-db/tree/master/Data

We merged the XED tables into our DB about a year ago.
