### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by PELock** [asmjit/asmjit#231]
Ok, let me tell you a story of a developer who wants donations but doesn't like to keep the information about the donors.

It's not about the money, I support plenty of programming projects with smaller and bigger amounts of money but I find it very **dishonest** to ask for donations, keep the donations section and then remove information about the donors (even after a few years).

I have supported this project since its beginning (I found about it in 2010). I even wrote an article to the programming press in 2013 with AsmJit in it, so it could reach wider audience:

https://www.pelock.com/articles/polymorphic-encryption-algorithms

(with a link to your site Petr, who would tell!)

I check this project from time to time to see what's new, a week ago I have noticed removed information about my donations, I made a comment here. Petr didn't respond to the comment, didn't send me an email, but got **angry** when I wrote about it here.

You would like to keep it quiet don't you Petr?

To be clear, I made a few donations to Petr. Yesterday he told me it was a deal between two of us to put my link for the donated money. I didn't think much about it because it was in 2010 (!), but I have searched my emails and let us see that again:

**20 april 2010**

> Hi Bartek,
> 
> I'd like to thank you for your generous donation.
> 
> If you want **I can add a link to your name and your site** under the
> Donation in AsmJit main page (I looked at your site and you are
> interested in assembler so this is also related page). You are **first**
> **who donated to the AsmJit project** and you have my respect.
> 
> Thank you!
> 
> -- 
> Best regards
> - Petr Kobalicek <http://kobalicek.com>

So you wanted to put the link yourself! Damn dude, you don't even know what you have said. Back then this project wasn't that popular and it was really helpful to me.

I made those donations without expecting anything in return.

Petr want to disclose the donations amounts (what a nice fellow), so here you go:

2010.04.19 (can you believe it?) - 25 EUR
2012.12.14 - 25 EUR
2015.01.11 - 50 EUR
2016.03.26 - 25 EUR

Now let me quote what you said in 2010 **"You are first who donated to the AsmJit project and you have my respect."**

What a nice guy this Petr and I thought I was the crazy one before I have checked my past emails...

Now back in 2019 my donations were called paid advertisements:

> Hi Bartosz,
> 
> It's sad that you have chosen a public channel to resolve a personal matter between us. I really appreciate all donations, including yours, however, I think that we should differentiate between a donation and a paid advertisement. You "donated" to advertise your own product and I kept that advertisement for a very long time, however, I don't consider your donation as a lifetime obligation to provide you advertisement of your commercial product.
> 
> Initially I wanted to fix this by keeping you on the list by changing the text it to the current donors format, but since you escalated it rather quickly (without even trying to contact me directly) I suggest to return you back all your donations so we can just move on without wasting more time on this. Just send me your IBAN so I can make the payment. I verified the total sum I received from you was ~120.55 EUR (4 payments total, last payment from March 2016), the PayPal archive doesn't display fees so I will send you the exact amount that I have received. Let me know if it's not the correct amount, it's just what I have found in history.
> 
> And a last thing. Would you mind me sharing the total amount I received from you and the last transaction date on that issue page? Since you created it and made this thing public with the intention to hurt the project I think it would be fair to add some economic details there so a possible reader can make his own picture about the matter.
> 
> Best,
> Petr
> 

Keep the money, but you have lost my respect.

**Comment by yzrmn** [comment]
Cheap shot dude...

**Comment by kobalicek** [comment]
I tried to solve this privately instead of making it a community thing as this was rather personal, however, the communication didn't end up well. The sudden change was of course not meant positively.

I think that in any way we should stay civilized here and don't let misunderstanding or anger change how we react or behave to each other.

**Comment by PELock** [comment]
Read above.

**Comment by kobalicek** [comment]
I think sharing the whole communication would be more transparent since you already started this nonsense.

**Comment by PELock** [comment]
Sure thing, here you go, after I made a donation I sent you the link to my site:

> Hello Petr,
> 
> Tuesday, April 20, 2010, 1:57:37 AM, you wrote:
> 
> > Hi Bartek,
> 
> > I'd like to thank you for your generous donation.
> 
> > If you want I can add a link to your name and your site under the
> > Donation in AsmJit main page (I looked at your site and you are
> > interested in assembler so this is also related page). You are first
> > who donated to the AsmJit project and you have my respect.
> 
> Thanks man, I'm developing a copy protection system called PELock
> (struggling with a new version relese) and when Im done with it I will
> probably use AsmJit for my new experimental project of an exe packer
> with dynamically created exe code, so if you want to link to my site,
> please link to
> 
> www.pelock.com "PELock"
> 
> at least its english site and has some asm related projects too (like
> an assembly obfuscator). Keep on developing, I will donate more often :)

How's that a paid ad, when you wanted to put it yourself as a thank you for the first donation?

Don't you even feel bad, accusing me of something that didn't even happen?

In 2016 I wanted to advertise in AsmTK project for 150 EUR, but you refused (you didn't want to make **this kind of affiliation** with me, whatever that means), that was the only case I wanted to pay for a link.

**Comment by PELock** [comment]
I thought I didn't remember the facts correctly in our recent emails, but the good thing I had it all saved and I don't feel guilty, because at first I thought I have paid for the link in AsmJit project, but now we all can see you came with that yourself.

**Comment by kobalicek** [comment]
For documentary purposes I'm attaching the whole communication here, because I think it's important for understanding the context. I thought about handling this differently, but I have a weird feeling that it ended like this in all alternative universes.

I would also like to say "sorry" to the community. In my opinion this issue should have never been opened and the community of open source project should not be used as a jury in a personal dispute between 2 people.

My proposal of fixing this is simple. Since I don't have the information to transfer the donated money back (no more PayPal), I would like to donate the same amount in BTC to some other open-source project on behalf of PELock. I thought about x64dbg as they seem to have a good relation with Bartosz and accept crypto.


[So here is the communication]

> Hello Petr,
>
> Saturday, January 19, 2019, 2:59:42 AM, you wrote:
>
> > Hi Bartosz,
> >
> > It's sad that you have chosen a public channel to resolve a
> > personal matter between us. I really appreciate all donations,
> > including yours, however, I think that we should differentiate
> > between a donation and a paid advertisement. You "donated" to
> > advertise your own product and I kept that advertisement for a very
> > long time, however, I don't consider your donation as a lifetime
> > obligation to provide you advertisement of your commercial product.
>
> I wrote a comment first, but you didn't respond at GitHub or in email.
>

I don't think a comment under a commit is a proper way of establishing
communication between us about something like this. I don't think making
such communication public makes sense as nobody can verify what happened
anyway, so what did you try to accomplish?

> You are wrong. I have donated multiple times and I can prove it,
> I have checked the history of our conversations and the first
> time I have donated I didn't ask for nothing, I have asked
> for the link in 2nd donation request. But there were 2 more.

I already calculated it (below) and just wanted to verify the final amount
with you. I never said you haven't donated or miscounted the number of
donations, so please let's not turn this into something it isn't.

> > Initially I wanted to fix this by keeping you on the list by
> > changing the text it to the current donors format, but since you
> > escalated it rather quickly (without even trying to contact me
> > directly) I suggest to return you back all your donations so we can
> > just move on without wasting more time on this. Just send me your
> > IBAN so I can make the payment. I verified the total sum I received
> > from you was ~120.55 EUR (4 payments total, last payment from March
> > 2016), the PayPal archive doesn't display fees so I will send you
> > the exact amount that I have received. Let me know if it's not the
> > correct amount, it's just what I have found in history.
> >
> > And a last thing. Would you mind me sharing the total amount I
> > received from you and the last transaction date on that issue page?
> > Since you created it and made this thing public with the intention
> > to hurt the project I think it would be fair to add some economic
> > details there so a possible reader can make his own picture about the
> > matter.
>
> Keep the money, you deserve it, but if you are going to play
> the victim card I can gladly dislose all the financial
> information so people can see I have asked for the link
> at one time, but donated 3 more times and you gladly took
> the money.
>

I'm not trying to play any card here. I'm trying to make us even in a
polite way so we both can move on without a feeling that one owes something
to the other. Remember that it was you who started this publicly. So if
this stays public then I would like to disclose the amount as i think it's
very important considering what you wrote in that issue. So as a result I
want to return you what you have invested, because I disagree with your
methods and the way you started dealing with it.

> I don't get it, I have supported you when nobody else
> did it, but now when your project is big and you obviously
> don't need the money, you're forgetting about the people
> who have helped you at the beginning.

You have no information about the number of donations that I have received
nor their amounts, so please stop these speculations. For your own
information - donations are symbolic to me - they are nice and I'm glad
when somebody appreciates my work, but it's more about the appreciation
than finance to me. I would not be working on asmjit or other open source
projects if I wanted to make more money. I love sharing my work and I don't
demand anything in return.

> So keep the money, forget about me, I will remove the comment
> from GitHub.

After all of this I don't want to keep the money and that's what I'm trying
to tell you. I don't even insist on sharing any details of the issue
publicly if we can just resolve it quickly and quietly without further
escalation. For me this is not worth it, it doesn't move the project
anywhere, and it distracts me from other work that I wanna do. So please
let's do the right thing to finally resolve this so we can move on.

[[Reply - PELock]]

Hello Petr,

Is anything from this list false?

1. I have donated 3 times without requesting anything in return
2. I have donated one time for the link (2nd donation)
3. Fine, you could remove the link, I agree with that
4. So why do you keep the donations list if I'm not there (just a name)?
5. You don't want the money but you gladly accepted it back then

It just seems you're not very decent and honest person.

I have supported many, many reversing and programming projects and
this is the first time someone doesn't want to mention the donor just
because he has the money now. This is another definition of low level.

[[Reply - Petr]]

I'm kindly asking you to read again what I have written. I believe the
outcome would be different if we started the whole thing differently,
but now it's too late to do that, because I just don't like where this
went and I don't want to make it worse. I would really appreciate if you
send me the IBAN so we can finally resolve this and move on. I'm asking
you like third time and you keep only adding more stuff that I'm not
interested in.

I really don't understand why you make such a drama out of it. We have
different opinions and that's it, life goes on, no need to judge others
and complicate it.

[[Reply - PELock]]

Hello Petr,

And I don't understand why is it so big problem for you to leave
donors names on your page (I'm not asking for the link), does it hurt
your feelings or what? Are you ashamed to take donations? If so
and you want to be true to yourself you should remove this sections
completely, because you don't even know how to handle it properly.

I want you to keep the money and think how dishonest your actions are.

You deserved donations back then, if I knew how vile person you are I
wouldn't donate a cent to you.

Please don't write to me again.

**Comment by PELock** [comment]
I never paid for any advertisement, I thought I did because you said so in the recent emails, but as we all can see you came up with this idea first.

**If you are so stubborn to NOT include my name on your donors list, even if I supported your project from day one, just because you are angry that I showed you were wrong and donations didn't have any strings attached, it's just another reason to not make any donations to you or any of your projects, because you are dishonest person and you have your supporters for nothing.**

**Comment by kobalicek** [comment]
Maybe linking https://github.com/asmjit/asmjit/issues/131 would help others understand why I have refused your donations after 2016 and why I think this couldn't end up differently.

**Comment by PELock** [comment]
Do you want to say you were **offended by the reported bugs** too, that could be fixed with changing 1 function to another to keep your software backward compatible (what a terrible idea to keep your software backward compatible, I know)?

It's getting better and better.

**Comment by nelson2005** [comment]
Dude's a troll. I've got PayPal, assuming that 125 euro is the amount, I'd be happy to send it to him for you. On Jan 19, 2019 4:15 PM, Bartosz Wójcik <notifications@github.com> wrote:Do you want to say you were offended by the reported bugs too, that could be fixed with changing 1 function to another to keep your software backward compatible (what a terrible idea to keep your software backward compatible, I know)?
It's getting better and better.

**Comment by PELock** [comment]
Can't argue with the facts that's why you call me names? Send it to the animal shelter if you have spare money and don't be a douche (again). I never said I want it back, can't you read?
