### ISSUE TITLE
'asmjit::X86Builder' cannot instantiate abstract class

### ISSUE THREAD

**Issue by LeonBlade** [asmjit/asmjit#235]
I didn't want to post an issue for this because it's likely a user error, but I created a clean project entirely to figure this out and it still confuses me.  I saw that `X86Builder` along with many others use `ASMJIT_VIRTAPI` which I believe is the source of my issue.  I'm trying to use `CodeBuilder` as described in the readme but I'm unable to with this issue.

Thank you.

**Comment by kobalicek** [comment]
Hello, I would recommend using next-wip branch if you need the Builder concept. The reason is that I didn't want to do breaking changes in master to fully support the builder concept so it's only fully working in next-wip.

This branch will be soon merged into the master so I would not be worried about stability.

**Comment by LeonBlade** [comment]
I was under the impression it worked in the master branch based on the README.  Thank you for your clarification!  Sorry for creating an issue again, perhaps though it will help someone else.
