### ISSUE TITLE
Passing 128bit sized arguments doesn't work

### ISSUE THREAD

**Issue by christophhart** [asmjit/asmjit#236]
I am pretty sure I am doing something wrong, but I can't figure out how to pass 128bit arguments (eg. a `__m128` value) into a JITted function.

The minimal example:

```cpp
typedef __m128(*Func)(__m128);

JitRuntime rt;                          
StringLogger l;

CodeHolder code;                        
code.init(rt.getCodeInfo());            
code.setLogger(&l);
X86Compiler cc(&code);                  

FuncSignatureX sig;
sig.setRet(TypeId::kF32x4);
sig.addArg(TypeId::kF32x4);

cc.addFunc(sig);      

auto pReg = cc.newXmmReg(TypeId::kF32x4);
cc.setArg(0, pReg);
auto vReg = cc.newXmmReg(TypeId::kF32x4);
		
cc.movaps(vReg, pReg);     
cc.ret(vReg);              
cc.endFunc();                           
cc.finalize();                          

Func fn;
rt.add(&fn, &code);         

__m128 v = _mm_set_ps(1.0f, 2.0f, 3.0f, 4.0f);

auto result = fn(v);                      

```

produces this assembly

```asm
L0:
mov rcx, rsp
movaps xmm1, oword [rcx+40]             ; movaps v0, oword [$__args+40]
movaps xmm0, xmm1                       ; movaps v1, v0
L1:
ret
```

but the result value contains garbage. Any clues?

**Comment by kobalicek** [comment]
I would recommend not doing this atm. I think it will work on non-Windows ABIs, but fail on Win64, because Win64 specifies that such argument must be passed by reference. I started some related work to support such scenario in next-wip branch (this behavior is supported there), but it's too early to use it.

For now just pass the data by pointer, you will not get worse code on Win64.

**Comment by christophhart** [comment]
Thanks for the quick response, using pointer arguments works like a charm. Feel free to close.
