### ISSUE TITLE
Question: Calling external functions with Assembler

### ISSUE THREAD

**Issue by thiagomacg** [asmjit/asmjit#263]
Hi

I wanted to know if and how I can call external functions say from a library.

Say for example call function std::cos.

I'm using the Assembler class. 

I saw some examples using Compiler.
I need to keep using the Assembler class. Some tips ?

**Comment by kobalicek** [comment]
You have to do the call preparation and the actual call yourself, because the Assembler has no information about ABI, dirty registers, stack frame, etc...

I think you can still use the FuncAPI helpers, but the assembling is up to you. At the moment only `Compiler` can do calls as it also allocates registers and manages stack, so for that tool it's natural to be able to call other functions, but with Assembler/Builder this is completely up to the user how the instructions are serialized.

**Comment by thiagomacg** [comment]
Hello, 
I decided to use Compiler to call external functions.

```

auto seno = [&](double value) {
            size_t valueOffset;
            double seno = static_cast<double_t>(std::sin(value));
            constPool.add(&seno, sizeof(double), valueOffset);
            return asmjit::x86::ptr(constPoolLabel, valueOffset);
};

asmjit::x86::Gp reg = c.newIntPtr("reg");
double test = 90.0;
auto call_a = c.call(seno(test), asmjit::FuncSignatureT<double_t>());
call_a->setRet(0, reg);

c.cvtsi2sd(asmjit::x86::xmm1, reg);



```

However, still the above code snippet still has error. I am trying to create a function that receives and returns a double. For the call method I used the approach with Mem. At the end I need to save the result in the variable xmm1.

I can't identify the error. The sine function is called correctly. But for the final assembler generation error occurs.
