### ISSUE TITLE
Performance of asmjit

### ISSUE THREAD

**Issue by certik** [asmjit/asmjit#300]
Thanks for creating this very nice library. I am looking for a library to generate machine code in the [LFortran](https://lfortran.org/) compiler. In terms of functionality I think `asmjit` does exactly what I was looking for. However, it seems the speed of code generation (compiling) is not optimal. I have written a [prototype x86 code generation](https://gitlab.com/lfortran/lfortran/-/blob/00e58cc1e6ba8884f270be115e94d8cd51cb95f4/src/lfortran/codegen/asr_to_x86.cpp) from scratch, with the goal of compiling as quickly as possible. Then I compared it to `asmjit` and it seems unfortunately that `asmjit` is slower. Is there anything that I might be doing wrong? Here is the benchmark I tried:
```c++
#include <asmjit/x86.h>
#include <iostream>
#include <stdio.h>
#include <string_view>
 
using namespace asmjit;
 
int main(int argc, char* argv[]) {
  using namespace asmjit::x86;
 
  // Create a custom environment initialized to 32-bit X86 architecture.
  Environment env;
  env.setArch(Environment::kArchX86);
 
  CodeHolder code;                  // Create a CodeHolder.
  code.init(env);                   // Initialize CodeHolder with custom environment.
 
  // Generate a 32-bit function that sums 4 floats and looks like:
  //   void func(float* dst, const float* a, const float* b)
  x86::Assembler a(&code);          // Create and attach x86::Assembler to `code`.
 
  int N = 1000000;
  for (size_t i = 1; i < N; i++) {
      a.mov(eax, dword_ptr(esp, 4));    // Load the destination pointer.
      a.mov(ecx, dword_ptr(esp, 8));    // Load the first source pointer.
      a.mov(edx, dword_ptr(esp, 12));   // Load the second source pointer. 
  }
 
  a.ret();                          // Return from function.
 
  // We have no Runtime this time, it's on us what we do with the code.
  // CodeHolder stores code in Section, which provides some basic properties
  // and CodeBuffer structure. We are interested in section's CodeBuffer.
  //
  // NOTE: The first section is always '.text', it can be retrieved by
  // code.sectionById(0) or simply by code.textSection().
  CodeBuffer& buffer = code.textSection()->buffer();

//  std::string_view c((const char*)buffer.data(), buffer.size());

//  std::cout << c;

  return 0;
}
```
I commented out outputting the data, as I don't want to benchmark that. I am only interested how quickly `asmjit` can generate machine code. Here is the corresponding benchmark using LFortran's prototype x86 codegen:
```c++
#include <iostream>
#include <sstream>
#include <lfortran/codegen/x86_assembler.h>
using LFortran::X86Reg;
int main() {
    Allocator al(1024);
    LFortran::X86Assembler a(al);

    size_t N = 1000000;
    for (size_t i = 1; i < N; i++) {
        X86Reg base = X86Reg::esp;
        a.asm_mov_r32_m32(X86Reg::eax, &base, nullptr, 1, 4);
        a.asm_mov_r32_m32(X86Reg::ecx, &base, nullptr, 1, 8);
        a.asm_mov_r32_m32(X86Reg::edx, &base, nullptr, 1, 12);
    }
    a.asm_ret();

//    a.save_binary("a.out");
}
```
I checked that the generated binary is identical to `asmjit`. I use Ubuntu 18.04 with g++-10 and the `Intel(R) Xeon(R) CPU E3-1505M v6 @ 3.00GHz` processor. I compile with `-O3 -march=native`. Results:

asmjit: 0.062s
LFortran: 0.043s

This is a significant 30% speedup over `asmjit`, and every little bit counts, as the goal of this x86 backend is compilation speed in Debug mode. In Release mode, the compiler uses LLVM which is much slower, but it can optimize the code well.

This is obviously an artificial benchmark, but it seems that it benchmarks how quickly the `mov_r32_m32` instruction can be generated. I haven't tried something more complicated.

**Comment by kobalicek** [comment]
Thanks for the benchmark! I think that this is just a price to pay for more features. AsmJit doesn't have specific methods for instruction groups, it basically serializes everything into a single function that is responsible for emitting all possible instructions, so there is code that has to query an instruction from an instruction database and then to check the instruction group and its operands. This is basically the 50% extra compared to your implementation in which you can call a specific function that knows that you are emitting `mov reg, [reg]`. AsmJit has to do some checks and especially `mov` has many forms (control/debug registers, segment registers, immediate forms, ...). However thanks to this design AsmJit provides a lot of features to its users and also a complete instruction database.

I'm actually quite surprised the overhead is that low, I always thought that it would be much greater although I optimized the emit() implementation a lot and it's definitely not a beauty.

My recommendation would be to not benchmark just the assembler, but to try to benchmark the whole thing, because from my experience the instruction encoding is usually negligible compared to other parts of the code generator. What I mean is that there is some code that is executed before invoking the assembler, so check how much it does compared to the assembler to see, because if you need 1s + 0.062s vs 1s + 0.043s then I would say it doesn't matter and it's worth to not spend time on writing your own assembler, however if you get 0.01 + 0.06 vs 0.01 + 0.04 then maybe you would want to.

I would definitely benchmark more instructions and use cases to get a better picture of whether the performance of AsmJit is acceptable or not. AsmJit is definitely not a silver bullet, but people that use it in their projects are usually very happy as it comes with many useful features that are handy during development (and possible to turn on in production too).

**Comment by certik** [comment]
Thanks @kobalicek! I think it is clear to me now:

* `asmjit` provides more functionality thanks to its design, and the price seems to be (up to) 50% slowdown over my direct solution.

* This extra price might be negligible if I benchmark the whole backend+`asmjit` vs. backend+`my codegen`, because the backend itself takes time. I think the only way to know is to create a demo backend for LFortran using `asmjit` and benchmark it. I'll do that.

* I like the features of `asmjit` and I think I could use a lot of them, including the JIT part (LFortran currently uses LLVM JIT for interactive usage). So I think I will create and maintain the `asmjit` backend anyway, that way I can experiment with it, and decide later if to use it by default or my own.
