### ISSUE TITLE
About riscv

### ISSUE THREAD

**Issue by wky9710** [asmjit/asmjit#332]
1. Is it pratical if I want to make it compatible with RISC-V backend? By imitating codes in x86 backend? 
There is riscv in _src/asmjit/core/environment.h_, so maybe all ISAs in that file can be supported...
2. Is there a minimal file set that I can make sure the new ISA works, like only implement codeholder, assembler, emitter, instdb and I can see the easiest RISCV output(not the complete instruction set, even a _mov & ret_ is ok) on a RISCV host machine? (By the way I'm using qemu, not real riscv machine, and it should work as well...)
3. I noticed this project is still developing ARM backend, seems it has taken a long time, so is there any difficulties or traps in supporting a new architecture?
Really thanks :)

**Comment by kobalicek** [comment]
I think that if you want to develop a new backend the easiest way would be to study how the current aarch64 was developed.

The biggest problem is instruction tables, because AsmJit requires some information for other tools (Builder / Compiler). In general each instruction is categories and then the assembler implements that category. So multiple instructions can share how they are emitted. You should only start with Assembler and add Builder/Compiler support later (it's not that much code and even I can do that provided that both Assembler and instruction database work).

**Comment by wky9710** [comment]
ok, I'll try with Assembler first, hope it goes well XD
thank (:3|____)

**Comment by kobalicek** [comment]
BTW let me know if you need any help with the design. There is a public gitter channel where you can ask questions if you need.

**Comment by SpriteOvO** [comment]
@wky9710 Hi! I would like to know if you are still working on this and have any updates?
