### ISSUE TITLE
Suggestion about instruction identifiers (Inst:kId...)

### ISSUE THREAD

**Issue by Nekotekina** [asmjit/asmjit#351]
Hello, I had a tiny convenience problem while choosing between SSE and VEX instructions. Most SSE instructions have VEX counterparts with "v" at the start. While experimenting with a code that is able to choose between those two (and AVX-512 as a bonus), I noticed the following inefficiency. I tried to use macro that adds "v" to base names like xorps.
1) ASMJIT uses macro that essencially duplicates textual name, as xorps and Xorps.
2) There is no way to capitalize part of the identifier in macro, so it has to be explicit.
3) If I want to prefix Xorps with V, I cannot do it. I have to rewrite it as Vxorps!
4) I may want to pass the ID itself to a subroutine in order to handle some of the instructions differently. But now I either have to spell it multiple times, or use something inefficient like string comparison.
I think there would be no problems if instruction IDs were in lowercase from the start, allowing very efficient user macro.

Example monstrousity, of course it could be written differently but lowercase IDs would simplify this a lot:
```C++
#define EMIT(inst, dst, src0, ...) c.emit_helper<true>(#inst,             \
	[&](auto dst, auto, auto... args) { ensure(!c.inst(dst, args...)); }, \
	[&](auto... args) { ensure(!c.v##inst(args...)); },                   \
	[&](auto... args) { ensure(!c.evex().v##inst(args...)); },            \
	dst, src0, __VA_ARGS__)

// Emit with broadcast fix for AVX-512 version
#define BCST(inst, bsfx, dst, src0, ...) c.emit_helper<false>(#inst,      \
	[&](auto dst, auto, auto... args) { ensure(!c.inst(dst, args...)); }, \
	[&](auto... args) { ensure(!c.v##inst(args...)); },                   \
	[&](auto... args) { ensure(!c.evex().v##inst##bsfx(args...)); },      \
	dst, src0, __VA_ARGS__)

// Emit instruction with the same arg count in SSE/AVX versions
#define LDST(inst, ...) c.emit_helper<true>(#inst,             \
	[&](auto... args) { ensure(!c.inst(args...)); },           \
	[&](auto... args) { ensure(!c.v##inst(args...)); },        \
	[&](auto... args) { ensure(!c.evex().v##inst(args...)); }, \
	__VA_ARGS__)
```

**Comment by kobalicek** [comment]
Hi, thanks for the issue!

I think you are right that it's not possible to simply substitute instruction names in a macro as the casing stands in the way. However, I'm not sure AsmJit should change because of this as all constants are consistent across the library. I can see that you have also some stuff for AVX-512, but that has problems too as some instruction names targeting AVX-512 have changed (like `vpxor` vs `vpxord` on AVX-512 side).

I think that in general you can solve this by having a template or a constexpr function that would do the mapping, and use that in the macro instead.

For example you can use something like this (compiler explorer example):

```c++
#include <stdint.h>

typedef uint32_t InstId;

template<InstId instId>
struct SSEToAVX {};

#define DEFINE_SSE_TO_AVX_MAPPING(SSEInstId, AVXInstId) \
template<> struct SSEToAVX<SSEInstId> { enum { kAVXInstId = AVXInstId }; }

DEFINE_SSE_TO_AVX_MAPPING(0, 1);
DEFINE_SSE_TO_AVX_MAPPING(1, 4);
DEFINE_SSE_TO_AVX_MAPPING(2, 551);
DEFINE_SSE_TO_AVX_MAPPING(3, 122);

uint32_t func() {
    return SSEToAVX<3>::kAVXInstId;
}
```

This would have the ability to also give you AVX-512 instruction in case of an instruction that has a different name, and also it could tell you about changes in operands / etc... I think sooner or later that would be the problem to fix.

To be honest I would go the opposite approach if I was designing a codegen - I would write everything as it was AVX and then I would just use SSE if AVX was not available, and in case destination and source registers are not the same a simple MOVDQA would be added before the instruction. This way you will be able to use a modern non-destructive destination approach in your code and just compile to SSE when it's not available.

**Comment by Nekotekina** [comment]
I solved this differently, the only thing that bugs me is id capitalization style after all.
```C++
using enum asmjit::x86::Inst::Id;
emit_binary_op(4, kIdMovdqa, kIdPaddd, kIdVpaddd, kIdVpaddd, std::forward<A>(a), std::forward<B>(b));
```
It's just not suited for assembly instruction names, and there is no magic to hide it really. Just a cosmetic issue.

**Comment by kobalicek** [comment]
I think there is not an ideal solution in the end:

  - if I change the naming a lot of AsmJit users will have broken code
  - if I add a redundant naming I would have to maintain it

At the moment it's just consistent with other enums, and that's what I prefer. I think making this easy for macros is also not really useful as there are instructions like and, or, xor, which are keywords and are `and_`, `or_`, `xor_` in assembler. So whatever I do there will be exceptions in how ID is named and how instruction is named in assembler.

**Comment by Nekotekina** [comment]
Okay, thanks for explaining the reasoning. I guess I'll close it then.
