### ISSUE TITLE
Why not merge 'aarch64' branch into 'master'?

### ISSUE THREAD

**Issue by lei-april** [asmjit/asmjit#353]
The aarch64 backend looks feature-complete already. Is there any plan to merge it into the 'master' branch? If not, what are the obstacles?

**Comment by kobalicek** [comment]
Yeah it's planned.

Reasons why it was not merged yet:
  - Not all instructions are provided yet (no SVE/SVE2/newer extensions)
  - Not all features are implemented (instruction validation is missing)
  - The plan was to merge aarch64 with 32-bit ARM as well (but this is not a requirement)

I'm currently working on bringing also 32-bit ARM support to AsmJit, which will include a different approach of generating instruction tables (including generating also the assembler). If there is a time I would like to make AArch64 generator to use this new approach instead of the current hack as it's much more reliable and much easier to maintain / add new instructions.

The plan was also to kind of unify 32-bit ARM and 64-bit ARM, but I will not try to do this (there is just too many differences that make this almost impossible).

**Comment by lei-april** [comment]
> BTW Erlang OTP already uses aarch64 and we have an agreement that aarch64 branch will be merged before their next release so they can use upstream asmjit, so give it one month and aarch64 will be merged to master regardless of ARM32 status.

That's great news. Thanks!

**Comment by kobalicek** [comment]
It has been merged, closing, thanks :)
