### ISSUE TITLE
Reading register values

### ISSUE THREAD

**Issue by phillvancejr** [asmjit/asmjit#377]
Can I read a register value on the C++ side? For example I'd like to know the value of x86::rsp or x86::rax. Is there a register.value() or something similar?

**Comment by kobalicek** [comment]
If you generate code that you want to debug in some way, you should move the content of the register you are interested in at the time you are interested in it into some memory location, for example, to inspect it later, or do something like that. The reason is that the content of registers is not there for long so reading anything on C++ side (running code translated by a C++ compiler) is already too late.

Or maybe I just don't understand the question, you should elaborate then :)

**Comment by hariv** [comment]
@kobalicek, when you say "move the content of the register you are interested in at the time into some memory location", how exactly would you do this?

For example, say I want to debug whatever is in register ebx at some point, can I just run:

``asm("\t movl %%ebx,%0" : "=r"(temp))`` where `temp` is a C variable? Or is there an asmjit specific way to do this?

**Comment by kobalicek** [comment]
BTW this is not asmjit specific - if you need to read a register in your C++ program, you would have to use inline assembler to do that (using the mentioned `asm` directive).

What I was trying to say is that reading some register in C++ is kinda weird, because you don't really control where variables are allocated, how big the stack is, etc... - this is all managed by the compiler, so I consider reading some register as basically reading a random value unless you have a longer instruction sequence within `asm` block that actually uses some specific instructions.

**Comment by phillvancejr** [comment]
What you said makes perfect sense. I didn't think about the fact that the code will already have have been compiled and run by the time I read it in C++. But for sake of completeness I can do something like `assembler.mov(imm(&my_cpp_variable), x86::rax)` in order to use a c++ variable as a memory location right? Or do I have to use inline asm? Thanks for your help on this!

**Comment by kobalicek** [comment]
Yes you can do that, but I wouldn't. It's a recipe for a disaster if you JIT function outlives that variable you encoded a pointer in the code to. It's perfectly fine for statics, that you want to use within the assembly code, but I would be very worried about using it for local variables.

Much better design is to pass a pointer to your JITed code and use that to read/write variables from - it makes the code much cleaner and there is no danger that it would write to an address that would be invalid at that point.

**Comment by phillvancejr** [comment]
Awesome, hey thanks for your help with this, regards!
