### ISSUE TITLE
CI Service for RISC-V port

### ISSUE THREAD

**Issue by alitariq4589** [asmjit/asmjit#404]
Hi everyone,
I hope everyone is doing great. I have gone through the RISC-V software ecosystem document and found out that asmjit is in progress to get ported to RISC-V. So, I was wondering if you folks need a (continuous integration) CI service for running tests on linux-based RISC-V real hardware (like starfive visionfive2 and hifive unleashed boards) or emulated instances (like QEMU). I have created such a CI service which you folks may find useful.

Kindly visit this link for onboarding and more information: https://cloud-v.co/

**Comment by kobalicek** [comment]
Hello,

I'm personally not looking for another CI service at the moment - it's just time consuming to support multiple CIs and from my experience it's just not convenient when builds start failing or are excessively long due to not enough runners on CI side (hello TravisCI).

When there is a RISC-V backend added it would first use QEMU, then maybe if there is a good solution we may run it on a real hardware, but if QEMU works I would kinda expect it to work on real hardware too.

**Comment by alitariq4589** [comment]
@kobalicek Thanks for letting me know. BTW, I will be here if you need such a service. So I am going to close the issue for time being.
