### ISSUE TITLE
No matter what I do. I am not able to get it working in my C++ CLI project.

### ISSUE THREAD

**Issue by ByteWhite1x1** [asmjit/asmjit#423]
I've tried to build the project pretty much in every possible way. https://www.unknowncheats.me/forum/c-and-c-/610766-asmjit.html

Needless to mention how frustrated this is...

**Comment by kobalicek** [comment]
Hello,

I have no experience with C++/CLI so I'm not able to do any kind of testing in this area.

If you consume asmjit as a statically linked library, don't forget to define ASMJIT_STATIC, otherwise asmjit would think it's a dynamically linked library. As a last resort, you can also embed asmjit in your project - just add .cpp files into your target, define ASMJIT_STATIC, and you should be done.

If none of these helps then I'm out of ideas as I'm not a C++/CLI user.

**Comment by ByteWhite1x1** [comment]
Hi. Thank you for fast reply.

I think you've bug somewhere in the latest asmjit sources. I copied an older asmjit sources (01/2023) from the Alcatraz project. And now my VS2019 C++ CLI project compiles just fine.

**Comment by kobalicek** [comment]
The reason why embedding always works is that the compiler uses the same compilation flags as the rest of the executable. I guess that if your project is C++/CLI and you use a statically compiled asmjit which has been compiled with different compilation flags possibly unaware of C++/CLI it could cause problems.

BTW there is a documentation about embedding in build instructions:

 - https://asmjit.com/doc/group__asmjit__build.html

If you think the wording is incorrect or confusing feel free to PR a documentation change :)
