### ISSUE TITLE
Relocatable code doc?

### ISSUE THREAD

**Issue by halivingston** [asmjit/asmjit#81]
My main interest in using asmjit is to take assembly code written for X86 and convert it to PIC. Is this something you'd recommend using your library? Is it even possible?

I couldn't find any doc or example suggesting "give AsmJit bytes of assembly and it will make it PIC".

**Comment by kobalicek** [comment]
Hi, I think this will be hard to do in asmjit as it was not designed for such task. I mean it's possible to write PIC, but since asmjit is mostly used to generate JIT code or remote code it knows how to translate relative displacements to absolute in case there is no other way.

In the future I plan ability to generate executables, which store information about relocations, but no work has been done regarding this.

**Comment by halivingston** [comment]
By PIC I mean relative instructions, that can be executed from anywhere. I don't care/want relocation tables. I want code generated such that it can start executing without any relocation info. Isn't your latest change about x86 PIC about that?

**Comment by kobalicek** [comment]
Ok in this case it's possible to use asmjit, however, the differences between x86 and x64 have to be handled by you. There might be some work needed to fully support PIC on x86 - for example referencing a label after a function body is not trivial without native support for relative addressing, which is only available on x64.

I think that you should try to make a small prototype and then we can discuss issues you faced.

BTW: No, my last change was about adding access to RIP register, which is only accessible on x64.

**Comment by kobalicek** [comment]
I'm closing this, if you need further questions let me know. In asmjit:next branch relocation information will be probably much easier to access even for people that don't want to use the default `JitRuntime`.
